name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04-arm
    steps:
    - uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: 壓縮檔案
      run: |
        mkdir compressed
        tar -czf compressed/files.tar.gz . 
    - name: 上傳工件
      uses: actions/upload-artifact@v3
      with:
        name: compressed-files
        path: compressed/files.tar.gz
